# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HodaTJIpjHeOs08Stbt080lJd1Y354nr
"""

print('Hello World')
print('1')